src/Entity/Messenger.php
<?php

namespace App\Entity;

use App\Repository\MessengerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessengerRepository::class)
 */
class Messenger
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $id_exp;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $id_recp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datee;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdExp(): ?string
    {
        return $this->id_exp;
    }

    public function setIdExp(string $id_exp): self
    {
        $this->id_exp = $id_exp;

        return $this;
    }

    public function getIdRecp(): ?string
    {
        return $this->id_recp;
    }

    public function setIdRecp(string $id_recp): self
    {
        $this->id_recp = $id_recp;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDatee(): ?\DateTimeInterface
    {
        return $this->datee;
    }

    public function setDatee(\DateTimeInterface $datee): self
    {
        $this->datee = $datee;

        return $this;
    }
}

src/Form/MessengerType.php
<?php

namespace App\Form;

use App\Entity\Messenger;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessengerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('message')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Messenger::class,
        ]);
    }
}

src/Controller/MessengerController.php
<?php

namespace App\Controller;

use App\Entity\Messenger;
use App\Entity\Post;
use App\Form\MessengerType;
use App\Repository\MessengerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/messenger")
 */
class MessengerController extends AbstractController
{
    /**
     * @Route("/", name="messenger_index", methods={"GET"})
     */
    public function index(MessengerRepository $messengerRepository): Response
    {
        return $this->render('messenger/new.html.twig', [
            'messengers' => $messengerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="messenger_new", methods={"GET","POST"})
     */
    public function new(Request $request,MessengerRepository $messengerRepository, Post $post): Response
    {
        $messenger = new Messenger();
        $form = $this->createForm(MessengerType::class, $messenger);
        $form->handleRequest($request);

        $messenger->setIdExp(1);
        $messenger->setIdRecp($post->getId());
        $messenger->setDatee(new \DateTime('@'.strtotime('now')));
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messenger);
            $entityManager->flush();

            return $this->redirectToRoute('messenger_new');
        }

        return $this->render('messenger/new.html.twig', [
            'messenger' => $messenger,
            'messengers' => $messengerRepository->findByidexp(1,$post->getId()),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="messenger_show", methods={"GET"})
     */
    public function show(Messenger $messenger): Response
    {
        return $this->render('messenger/new.html.twig', [
            'messenger' => $messenger,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="messenger_edit", methods={"GET","POST"})
     */

    /**
     * @Route("/{id}", name="messenger_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Messenger $messenger): Response
    {
        if ($this->isCsrfTokenValid('delete'.$messenger->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($messenger);
            $entityManager->flush();
        }

        return $this->redirectToRoute('messenger_new');
    }
}

templates/messenger/_delete_form.html.twig
<form method="post" action="{{ path('messenger_delete', {'id': messenger.id}) }}" onsubmit="return confirm('Are you sure you want to delete this message?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ messenger.id) }}">
    <button class="btn">Delete</button>
</form>

templates/messenger/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Messenger{% endblock %}

{% block body %}
    <h1>Edit Messenger</h1>

    {{ include('messenger/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('messenger_index') }}">back to list</a>

    {{ include('messenger/_delete_form.html.twig') }}
{% endblock %}

templates/messenger/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger index{% endblock %}

{% block body %}
    <h1>Messenger index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_exp</th>
                <th>Id_recp</th>
                <th>Message</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for messenger in messengers %}
            <tr>
                <td>{{ messenger.id }}</td>
                <td>{{ messenger.idExp }}</td>
                <td>{{ messenger.idRecp }}</td>
                <td>{{ messenger.message }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('messenger_new') }}">Create new</a>
{% endblock %}

templates/messenger/new.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Post{% endblock %}


{% block body %}

    {{ include('head.html.twig')  }}

{% for messenger in messengers %}
<tr>
    </br>
    <td>   {% if(messenger.idExp !=1)%}                         <h6 style="color: #bd2130">  <b> &nbsp;&nbsp;  &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp;  &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp;
                    &nbsp;&nbsp; {{ messenger.message }}  </b> </h6> {% endif%}</td>
    <td>
        {% if(messenger.idExp ==1)%}

            <form method="post" action="{{ path('messenger_delete', {'id': messenger.id}) }}" onsubmit="return confirm('Are you sure you want to delete this message?');">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ messenger.id) }}">
                 <h6 style="color: #003eff"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b> {{ messenger.message }}    &nbsp;  <button class="btn">X</button>  </b> </h6>

    </form>
        {% endif%}
    </td>
    </br>

</tr>

{% endfor %}
</br>
</tbody>
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('send') }}</button>
{{ form_end(form) }}
</div>
    </div>
    </div>

    {{ include('footer.html.twig')  }}
    {% endblock %}

templates/messenger/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger{% endblock %}

{% block body %}
    <h1>Messenger</h1>
<table class="table">
    <tbody>
    <tr>
        <th>Id</th>
        <td>{{ messenger.id }}</td>
    </tr>
    <tr>
        <th>Id_exp</th>
        <td>{{ messenger.idExp }}</td>
    </tr>
    <tr>
        <th>Id_recp</th>
        <td>{{ messenger.idRecp }}</td>
    </tr>
    <tr>
        <th>Message</th>
        <td>{{ messenger.message }}</td>
    </tr>
    </tbody>
</table>

<a href="{{ path('messenger_index') }}">back to list</a>

<div class="header_section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div><a href="index.html"><img src="images/logo.png"></a></div>
            </div>
            <div class="col-md-8">
                <div class="menu_text">
                    <ul>
                        <li class="last">Log in / Register</li>
                        <li class="last"><a href="#"><img src="images/search-icon.png"></a></li>
                        <li class="active">
                            <div id="myNav" class="overlay">
                                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                                <div class="overlay-content">
                                    <a href="index.html">Home</a>
                                    <a href="about.html">About</a>
                                    <a href="gallery.html">Gallery</a>
                                    <a href="contact.html">Contact</a>
                                </div>
                            </div>
                            <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>
                </div>
                </li>
                </ul>
            </div>
        </div>
    </div>


{% endblock %}