src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $destination;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombres_personnes;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * Reservation constructor.
     * @param $id
     * @param $destination
     * @param $date_debut
     * @param $date_fin
     * @param $nombres_personnes
     * @param $prix
     */

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNombresPersonnes(): ?int
    {
        return $this->nombres_personnes;
    }

    public function setNombresPersonnes(int $nombres_personnes): self
    {
        $this->nombres_personnes = $nombres_personnes;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('destination')
            ->add('date_debut')
            ->add('date_fin')
            ->add('nombres_personnes')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\LocationRepository;
use App\Repository\ReservationRepository;
use phpDocumentor\Reflection\Location;
use phpDocumentor\Reflection\Types\Null_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("home/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * ReservationController constructor.
     */
    public function __construct()
    {
    }

    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

// Method reserver !!
// add here !!
/**
 * @Route ("/reserve", name="reserver", methods={"GET"})
*/
public function reserver(Request $request, LocationRepository  $locationRepository): Response{
//    <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
    $reservation = new Reservation();
$location = new \App\Entity\Location();
//    $form = $this->createForm(ReservationType::class, $reservation);
//    $form->handleRequest($request);
//  if($request->request->get('prix')!=Null){
    $id = $request ->query->get('id');
    $nb= $request-> query->get('nb');
   // $dateDeb = $request -> get('dateDeb');
    $location = $locationRepository ->find($id);

    $reservation->setPrix($location->getPrix());
    $reservation->setDestination(        $location->getLocalisation());
    $reservation->setDateFin(new \DateTime('2021-01-01'));
    $reservation->setDateDebut(new \DateTime('2021-01-01'));
    $reservation->setNombresPersonnes($nb);

    $entityManager = $this->getDoctrine()->getManager();
    $entityManager->persist($reservation);
    $entityManager->flush();
    return $this->render('reservation/new.html.twig');

}

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request,LocationRepository $r): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        if($request->request->get('date')!=Null)
        {   //$reservation->setPrix(0);
        $reservation->setDateFin(new \DateTime($request->request->get('date-1')));
            $reservation->setDateDebut(new \DateTime($request->request->get('date')));

            $reservation->setDestination($request->request->get('select'));
            $reservation->setNombresPersonnes($request->request->get('nb'));
           // $entityManager = $this->getDoctrine()->getManager();
            //$entityManager->persist($reservation);
            //$entityManager->flush();
            //$formSent = $this-> createForm(ReservationType::class, $reservation);
            //$formSent->handleRequest($request);
            return $this->render('hotel.html.twig',[
 'locations' =>$r->findbb($reservation->getDestination(),$reservation->getNombresPersonnes()),
'nb'=>$reservation->getNombresPersonnes(),
                'dateDebut' => $reservation->getDateDebut(),

                'dateFin' => $reservation->getDateFin(),
                //'form' => $formSent->createView(),

            ]);
        }

else{
    return $this->render('reservation/new.html.twig', [
        'reservation' => $reservation,

    ]);

}

    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig',[
            'reservation' =>$reservation,

        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }


    /**
     * @Route("/home/new", name="reservation_new_front", methods={"GET","POST"})
     */
    public function newfront(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('front/reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/home/{id}", name="reservation_show_front", methods={"GET"})
     */
    public function showfront(Reservation $reservation): Response
    {
        return $this->render('front/reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/home/{id}/edit", name="reservation_edit_front", methods={"GET","POST"})
     */
    public function editfront(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('front/reservation_index');
        }

        return $this->render('front/reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/edit_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/edit_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/new.html.twig
{% block title %}New Reservation{% endblock %}

{% block body %}



    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('reservation_index') }}">back to list</a>



{% endblock %}

templates/reservation/show.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    {{ include('head.html.twig') }}

    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ reservation.destination }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ reservation.dateDebut ? reservation.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombres_personnes</th>
                <td>{{ reservation.nombresPersonnes }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ reservation.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>

    {{ include('reservation/_delete_form.html.twig') }}

    {{ include('footer.html.twig') }}
{% endblock %}