src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_utl;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datepost;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $message;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $solution;

    /**
     * @ORM\OneToMany(targetEntity=Reaction::class, mappedBy="Post")
     */
    private $reactions;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titres;

    public function __construct()
    {
        $this->reactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUtl(): ?string
    {
        return $this->id_utl;
    }

    public function setIdUtl(string $id_utl): self
    {
        $this->id_utl = $id_utl;

        return $this;
    }

    public function getDatepost(): ?\DateTimeInterface
    {
        return $this->datepost;
    }

    public function setDatepost(\DateTimeInterface $datepost): self
    {
        $this->datepost = $datepost;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getsolution(): ?int
    {
        return $this->solution;
    }

    public function setsolution(int $solution): self
    {
        $this->solution = $solution;

        return $this;
    }

    /**
     * @return Collection|Reaction[]
     */
    public function getReactions(): Collection
    {
        return $this->reactions;
    }

    public function addReaction(Reaction $reaction): self
    {
        if (!$this->reactions->contains($reaction)) {
            $this->reactions[] = $reaction;
            $reaction->setPost($this);
        }

        return $this;
    }

    public function removeReaction(Reaction $reaction): self
    {
        if ($this->reactions->removeElement($reaction)) {
            // set the owning side to null (unless already changed)
            if ($reaction->getPost() === $this) {
                $reaction->setPost(null);
            }
        }

        return $this;
    }

    public function getTitres(): ?string
    {
        return $this->titres;
    }

    public function setTitres(string $titres): self
    {
        $this->titres = $titres;

        return $this;
    }
}

src/Entity/Reaction.php
<?php

namespace App\Entity;

use App\Repository\ReactionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReactionRepository::class)
 */
class Reaction
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="reactions")
     * @ORM\JoinColumn(nullable=True)
     */
    private $post;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_utli;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $message;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?post
    {
        return $this->post;
    }

    public function setPost(?post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getIdUtli(): ?string
    {
        return $this->id_utli;
    }

    public function setIdUtli(string $id_utli): self
    {
        $this->id_utli = $id_utli;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block css %}
            {#{{ encore_entry_link_tags('app') }}#}
            <link rel="stylesheet" href="{{ asset('../../../assets/vendors/mdi/css/materialdesignicons.min.css') }}">

            <link rel="stylesheet" href="{{asset ('../../../assets/vendors/css/vendor.bundle.base.css')}}">

            <!-- endinject -->
            <!-- Plugin css for this page -->
            <!-- End plugin css for this page -->
            <!-- Layout styles -->
            <link rel="stylesheet" href="{{asset ('../../../assets/css/demo/style.css')}}">

            <!-- End layout styles -->
            <link rel="shortcut icon" href="{{asset ('../../../assets/images/favicon.png')}}" />

        {% endblock %}

        {% block js %}
            {#{{ encore_entry_script_tags('app') }}#}
            <script src=" {{asset ('../../../assets/vendors/js/vendor.bundle.base.js')}}"></script>

            <!-- endinject -->
            <!-- Plugin js for this page-->
            <!-- End plugin js for this page-->
            <!-- inject:js -->
            <script src="{{asset ('../../../assets/js/material.js')}}"></script>

            <script src="{{asset ('../../../assets/js/misc.js')}}"></script>

        {% endblock %}
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

templates/base1.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}PI Blog{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="/Assets/css/app.css">

            <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
            <link rel="canonical" href="{{ asset('index.html') }}">

        {% endblock %}
    </head>
    <body>
       <!-- <div class="site-header">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="logo">
                            <h2 class="text-uppercase">
                                WILDREAM
                            </h2>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 text-center">
                        <ul class="socials float-right mt-4 p-2">
                            <li><a href="#" class="p-2"><i class="fab fa-facebook"></i></a></li>
                            <li><a href="#" class="p-2"><i class="fab fa-twitter"></i> </a></li>
                            <li><a href="#" class="p-2"><i class="fab fa-instagram"></i> </a></li>
                            <li><a href="#" class="p-2"><i class="fab fa-linkedin"></i> </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>//-->
        <div class="main-nav">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <img src="/Assets/images/logowpng.png" class="mainlogo">
    <!--<a class="navbar-brand" href="#">Navbar</a>//-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Inscription</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Store
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Hotels</a></li>
            <li><a class="dropdown-item" href="#">Houses</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Tools</a></li>
          </ul>
        </li>
        <li class="nav-item">
         <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Contact</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" aria-label="Serch">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
        </div>
        <div class="container mt-4" >
            <div class="row" >
                {% block body %}

                {% endblock %}
            </div>
        </div>
        <footer class="text-center text-capitalize mt-4 bg-dark">
            <ul class="mt-3">
                <li>WILDREAM &copy;2021</li>
                <li><a href="#" class="p-2">A Propos</a></li>
                <li><a href="#" class="p-2">Politique de confidentialité</a></li>
                <li><a href="#" class="p-2">Contactez-Nous</a></li>
            </ul>
        </footer>
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
            <script src="https://kit.fontawesome.com/f9fb07255c.js" crossorigin="anonymous"></script>

            <script type="application/ld+json">{
                    "@context": "http://schema.org",
                    "@type": "Organization",
                    "name": "",
                    "url": "index.html"
                }
            </script>

            <script class="u-script" type="text/javascript" src="{{ asset('nicepage.js') }}" defer=""></script>

        {% endblock %}
    </body>
</html>

templates/basefront.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Sample Headline">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <meta name="generator" content="Nicepage 3.9.0, nicepage.com">

    <meta property="og:title" content="Locations">

    <meta property="og:type" content="website">
    <meta name="theme-color" content="#478ac9">

    <meta property="og:url" content="index.html">
    <title>{% block title %}Welcome!{% endblock %}</title>

    {% block css %}
        <link rel="stylesheet" href="  {{ asset('nicepage.css') }}" media="screen">
        <link rel="stylesheet" href=" {{ asset('location.css') }}" media="screen">

        <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
        <link rel="canonical" href="{{ asset('index.html') }}">
    {% endblock %}

    {% block js %}


    {% endblock %}
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

templates/footer.html.twig
</section>
<footer class="u-clearfix u-footer u-grey-80" id="sec-2e15"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1">
            <div class="menu-collapse">
                <a class="u-button-style u-nav-link" href="#">
                    <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;"><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
                            </symbol>
                        </defs></svg>
                </a>
            </div>
            <div class="u-nav-container">
                <ul class="u-nav u-unstyled"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Acceuil.html">Acceuil</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Evénements.html">Evénements</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Locations.html">Locations</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="forum.html">forum</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="autre.html">autre</a>
                    </li></ul>
            </div>
            <div class="u-nav-container-collapse">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                    <div class="u-sidenav-overflow">
                        <div class="u-menu-close"></div>
                        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Acceuil.html">Acceuil</a>
                            </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Evénements.html">Evénements</a>
                            </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Locations.html">Locations</a>
                            </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="forum.html">forum</a>
                            </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="autre.html">autre</a>
                            </li></ul>
                    </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
            </div>
        </nav>
        <img src="{{ asset('images/default-logo.png') }}" alt="" class="u-image u-image-round u-radius-10 u-image-1" data-image-width="1083" data-image-height="272" data-href="Acceuil.html" data-page-id="283736059">
    </div></footer>

</body>
</html>

templates/forum.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Post{% endblock %}


{% block body %}
    {{include ('head.html.twig')  }}
    <link rel="stylesheet" href="  {{ asset('nicepage.css') }}" media="screen">

    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link rel="canonical" href="{{ asset('index.html') }}">
    <link rel="stylesheet" href=" {{ asset('forum.css') }}" media="screen">



    <section class="u-align-center u-clearfix  u-section-2" id="sec-44be">
        <form class="d-flex" action="recherche" method="post">
            <input class="form-control me-2" type="search" placeholder="Search" name="recherche" aria-label="Search" aria-label="Serch">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div class="u-clearfix u-sheet u-sheet-1">
            <h2 class="u-text u-text-1"></h2>
            <p class="u-text u-text-2">Posez vos questions</p>

            {% for post in posts %}

                <div class="u-accordion u-expanded-width u-faq u-spacing-10 u-accordion-1">
                <div class="u-accordion-item">
            <a class="u-accordion-link u-active-palette-2-light-2 u-button-style u-palette-1-dark-1 u-radius-50 u-accordion-link-2" id="link-accordion-854e" aria-controls="accordion-854e" aria-selected="false">
                <span class="u-accordion-link-text">{{ post.titres }} {% if post.solution == 1%}   <img src="{{ asset('images/9.svg') }}" alt="" /> {% endif %} </span><span class="u-accordion-link-icon u-icon u-text-palette-1-light-2 u-icon-2"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 448 448" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-7f79"></use></svg><svg class="u-svg-content" id="svg-7f79" style=""><path d="m272 184c-4.417969 0-8-3.582031-8-8v-176h-80v176c0 4.417969-3.582031 8-8 8h-176v80h176c4.417969 0 8 3.582031 8 8v176h80v-176c0-4.417969 3.582031-8 8-8h176v-80zm0 0"></path></svg></span>
            </a>
            <div class="u-accordion-pane u-container-style u-opacity u-opacity-0 u-white u-accordion-pane-2" id="accordion-854e" aria-labelledby="link-accordion-854e">
                <div class="u-container-layout u-container-layout-2">
                    <div class="fr-view u-clearfix u-rich-text u-text">
                        <p>{{ post.message }}  <br> <br><a href=" {{ path('post_show', {'id': post.id}) }}"><img src="{{ asset('images/11.svg') }}" alt="" style="width: 50px;height: 50px;"/>
                             </a>    <a href=" {{ path('messenger_new', {'id': post.idUtl}) }}"> <img style="width: 50px;height: 50px;"src="{{ asset('images/chat.svg') }}" alt=""   />&nbsp;

                                </a></p>
                    </div>
                </div>

            </div>

<br> <br>
        </div></div>
            {% endfor %}  </div>
    </section>
<section class="u-align-center u-clearfix u-gradient u-section-2" id="sec-9910">
            <div class="u-clearfix u-sheet u-sheet-1">
                <div class="u-form u-form-1">

                    <form action="new" method="POST" style="padding: 50px;" >
                        <div class="u-form-email u-form-group">

                            <input type="text" placeholder="titre"  name="titre" class="u-border-1 u-border-grey-30 u-input u-input-rectangle" >
                        </div>
                        <div class="u-form-group u-form-message">

                            <textarea placeholder="message" rows="8" cols="100" name="message" class="u-border-1 u-border-grey-30 u-input u-input-rectangle" ></textarea>
                        </div>


                            <input type="submit" value="submit" class="u-btn u-btn-round u-btn-submit u-button-style u-radius-50">



                    </form>
                </div>
            </div>
            </div>
    </section>
    {{include ('footer.html.twig')  }}
{% endblock %}

templates/forum2.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Post{% endblock %}


{% block body %}
    <link rel="stylesheet" href="  {{ asset('nicepage.css') }}" media="screen">

    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link rel="canonical" href="{{ asset('index.html') }}">
    <link rel="stylesheet" href=" {{ asset('forum.css') }}" media="screen">



    {{ include('head.html.twig')  }}
    <section class="u-align-center u-border-4 u-border-grey-75 u-clearfix u-gradient u-section-1" id="sec-002b">

            <div class="fr-view u-align-center u-clearfix u-rich-text u-text u-text-1">
                <h1 style="text-align: left;">
                    <span style="line-height: 2.0;">{{ post.titres }}</span>
                </h1>
                <p style="text-align: left;">
                    <span style="line-height: 2.0;">{{ post.message }}  <br>    <br>   {{ post.datepost ? post.datepost|date('Y-m-d H:i:s') : '' }}</span>
                </p>
            </div>

    </section>
    <section class="u-align-center u-clearfix u-gradient u-section-2" id="sec-0c0d">
    {% for reaction in reactions %}

            <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
                <h6 style="text-align: left;">
                    <span style="line-height: 2.0;"> {{ reaction.idUtli }} </span>
                    <span style="line-height: 2.0;"> {{ reaction.message }}</span>
                    {{ include('reaction/_delete_form.html.twig') }}
                </h6>

        </div>

    {% endfor %}
    </section>
    <section class="u-align-center u-clearfix u-gradient u-section-3" id="sec-bf0e">
        <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">


            <div class="u-form u-form-1">
                <form action="../reaction/new" method="POST" class="u-clearfix u-form-spacing-15 u-form-vertical u-inner-form" style="padding: 15px;" source="custom" name="form">

                    <input  type="text" name="id" value="{{ post.id }}" hidden >
                    <div class="u-form-group u-form-message u-form-group-2">
                        <label for="message-6797" class="u-form-control-hidden u-label">Address</label>
                        <textarea placeholder="Address" rows="4" cols="50" id="message-6797" name="message" class="u-border-1 u-border-grey-30 u-input u-input-rectangle" required=""></textarea>
                    </div>
                    <div class="u-align-left u-form-group u-form-submit u-form-group-3">

                        <input type="submit" value="submit" class="u-btn u-btn-round u-btn-submit u-button-style u-radius-50">
                    </div>

                </form>
            </div>
        </div>

    </section>


    {{include ('footer.html.twig')  }}
{% endblock %}

templates/hotel.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    {{ include('head.html.twig') }}

<section class="u-align-center u-clearfix u-gradient u-section-1" id="sec-215f">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-1">Sample Headline</h2>
        <p class="u-text u-text-2">Sample text. Click to select the text box. Click again or double click to start editing the text.</p><!--products--><!--products_options_json--><!--{"type":"Recent","source":"","tags":"","count":""}--><!--/products_options_json-->
        <div class="u-expanded-width u-products u-products-1">
            <div class="u-repeater u-repeater-1"><!--product_item-->
               ><!--product_item-->
                {% for location in locations %}
    <div class="u-align-center u-container-style u-products-item u-repeater-item">
    <div class="u-container-layout u-similar-container u-valign-top u-container-layout-1"><!--product_image-->
        <img alt="" class="u-expanded-width u-image u-image-default u-product-control u-image-1" src="{{ asset( location.url ) }}"><!--/product_image-->
        <div class="u-align-center u-container-style u-grey-10 u-group u-group-1">
            <div class="u-container-layout u-valign-bottom u-container-layout-2"><!--product_title-->
               <h2 name="localisation">{{ location.localisation }}</h2>
                <h4 class="u-product-control u-text u-text-3">
                    <a class="u-product-title-link" name="type"><!--product_title_content-->{{ location.type  }}<!--/product_title_content--></a>
                </h4><!--/product_title--><!--product_price-->
<h5 name="dateDebut">{{ dateDebut|date('Y-m-d')}}</h5>
                <h5 name="dateFin">{{ dateFin|date('Y-m-d') }}</h5>
                <div class="u-product-control u-product-price u-product-price-1">
                    <div class="u-price-wrapper u-spacing-10"><!--product_old_price-->
                        <div class="u-hide-price u-old-price"><!--product_old_price_content--><td> </td><!--/product_old_price_content--></div><!--/product_old_price--><!--product_regular_price-->
                        <div name="prix" class="u-price u-text-palette-2-base" style="font-size: 1.25rem; font-weight: 700;"><!--product_regular_price_content-->{{ location.prix * nb }}<!--/product_regular_price_content--></div><!--/product_regular_price-->
                    </div>
                </div><!--/product_price-->
            </div>
        </div><!--product_content-->
        <div class="u-product-control u-product-desc u-text u-text-4"><!--product_content_content-->{{ location.description  }}<!--/product_content_content-->
            <!-- add button -->
{#            <a   href="{{ path('reserver') }}">reserver</a>#}
{#
            <a  href="{{ path('reserver', {'id': location.id, 'nb': nb, 'dateDeb': dateDebut  "f"}) }}">testttttt</a>
#}
            <a  href="{{ path('reserver')}}?id={{ location.id }}&nb={{ nb }}">testttttt</a>
            <!--div-- class="u-align-center u-form-group u-form-submit">
                <input type="submit" value="submit" class="u-black u-btn u-btn-round u-btn-submit u-button-style u-radius-50 u-btn-1">

            </div-->
            {% endfor %}</div><!--/product_content-->
    </div>
</div><!--/product_item--
                <tr>

                    </td>
                </tr>
            </div>  </div>  </div>
</section>




    {{ include('footer.html.twig') }}
{% endblock %}